<?php

namespace CarpoolingBundle\Repository;

/**
 * CarpoolingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarpoolingRepository extends \Doctrine\ORM\EntityRepository
{
}
