admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

carpooling:
    resource: "@CarpoolingBundle/Resources/config/routing.yml"
    prefix:   /

lost_object:
    resource: "@LostObjectBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /

index:
    resource: "@IndexBundle/Resources/config/routing.yml"
    prefix:   /

tutorat:
    resource: '@TutoratBundle/Controller/'
    type: annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation
