<?php

namespace LostObjectBundle\Repository;

/**
 * LostObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LostObjectRepository extends \Doctrine\ORM\EntityRepository
{
}
